# Generated by Django 4.2.6 on 2023-10-08 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("FinancialTransactions", "0002_category_expense_alter_entry_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
